const getData = async () => {
  try {
    undefined.find();
  } catch (error) {
    //
  }
};

getData();

console.log("Done!");
